sudo: required
services:
  - docker

before_install:
  - docker build -t uglysunshine/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run uglysunshine/react-test npm test -- --coverage

after_success:
  - docker build -t uglysunshine/multi-client ./client
  - docker build -t uglysunshine/multi-nginx ./nginx
  - docker build -t uglysunshine/multi-server ./server
  - docker build -t uglysunshine/multi-worker ./worker

  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push uglysunshine/multi-client
  - docker push uglysunshine/multi-nginx
  - docker push uglysunshine/multi-server
  - docker push uglysunshine/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multidocker-env
  bucket_name: elasticbeanstalk-us-east-1-565678810090
  bucket_path: docker_multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY